# Generated by Django 2.2.13 on 2021-02-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='new_text',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Новый Текст'),
        ),
    ]
