# Generated by Django 2.2.13 on 2021-02-04 13:28
from django.db import migrations


class Migration(migrations.Migration):

    def transfer_tags(apps, schema_editor):
        Article = apps.get_model('webapp.Article')
        for article in Article.objects.all():
            article.new_text = article.text
            article.save()
            # article.tags.set(article.tags_old.all())

    def rollback_transfer(apps, schema_editor):
        Article = apps.get_model('webapp.Article')
        for article in Article.objects.all():
            article.text = article.new_text
            article.save()
            # article.tags_old.set(article.tags.all())

    dependencies = [
        ('webapp', '0002_article_new_text'),
    ]

    operations = [
        migrations.RunPython(transfer_tags, rollback_transfer)
    ]
