# Generated by Django 2.2.13 on 2021-02-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210204_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='new_text',
        ),
    ]
