# Generated by Django 2.2.13 on 2021-02-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210204_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(default='new', max_length=15, verbose_name='Модерация'),
        ),
    ]
