# Generated by Django 2.2.13 on 2021-02-05 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_article_publish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время публикации'),
        ),
    ]
